services:
  app:
    build: .
    container_name: sync_scheduler
    restart: unless-stopped
    volumes:
      - "/storage:/storage"
      - "./configs:/mirror/sync_scheduler/configs:ro"
      - "./scripts:/mirror/sync_scheduler/scripts:ro"
    networks:
      - mirror
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 8192M
    stdin_open: true
    tty: true

networks:
  mirror:
    external: true
